apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # Labels for the Deployment object itself
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
    # The Deployment uses these to find and manage its Pods
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  # Template defines the Pods that will be created
  template:
    metadata:
      # These MUST match the 'selector' labels above
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672 # servie port
    targetPort: 5672 # container port